# 03 — Training

Fine-tune encoder models and run LLM baselines.  
All runs use the same hyperparameters — the only variable is which density column is used for weighting.

**Sections**
1. Configuration
2. Define experiments (dataset × density column)
3. Fine-tuning runs
4. LLM baselines
5. Results summary

In [1]:
import sys, os
if os.getcwd().endswith('notebooks'):
    os.chdir('..')

import json
import yaml
import pandas as pd

from src.training import TrainingConfig, train, run_baselines

c:\Users\Alexandre\miniconda3\envs\faiss2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Configuration

Edit `TrainingConfig` fields below to change model, hyperparameters, or output paths.  
All experiments in this notebook share the same config — only `density_column` varies per run.

In [2]:
CONFIG_PATH = "configs/datasets.yaml"
with open(CONFIG_PATH) as f:
    cfg = yaml.safe_load(f)

EMBEDDINGS_ROOT   = cfg["embedding"]["output_root"]
PREPROCESSED_ROOT = cfg["preprocessing"]["output_root"]
MODEL_NAME        = cfg["embedding"]["models"][0]
MODEL_SLUG        = MODEL_NAME.replace("/", "_")
K_VALUES          = cfg["embedding"]["k_values"]

# Russian is reference-only: not used for fine-tuning, only for density + eval
TRAIN_DATASETS    = cfg.get("train_datasets", ["toxigen"])

train_cfg = cfg["training"]

base_config = TrainingConfig(
    model_id     = train_cfg["models"][0],
    batch_size   = train_cfg["batch_size"],
    learning_rate= train_cfg["learning_rate"],
    num_epochs   = train_cfg["epochs"],
    max_length   = train_cfg["max_length"],
    random_state = train_cfg["random_state"],
    output_root  = train_cfg["output_root"],
)

print("Models         :", train_cfg["models"])
print("Epochs         :", base_config.num_epochs)
print("LR             :", base_config.learning_rate)
print("Train datasets :", TRAIN_DATASETS)
print("Output         :", base_config.output_root)

Models         : ['answerdotai/ModernBERT-base', 'tomh/toxigen_roberta']
Epochs         : 3
LR             : 2e-5
Train datasets : ['toxigen']
Output         : outputs/3_training

## 2. Define Experiments

Each experiment is `(dataset, density_column)`.  
- `density_column = None` → train without weighting (baseline encoder)
- `density_column = 'density_k5_ratio'` → weight by Russian/All ratio at K=5 on raw embeddings
- `density_column = 'density_pca_k5_ratio'` → same but PCA space

Edit the list below to add/remove experiments.

In [3]:
# Build experiment list: one fine-tune per (train_dataset × density_column)
# Russian is excluded — it is the reference group used for density, not for training.
density_columns = [None]  # baseline: no weighting
for k in K_VALUES:
    density_columns.append(f"density_k{k}_ratio")       # raw space
    density_columns.append(f"density_pca_k{k}_ratio")   # PCA space

experiments = [
    {"dataset": ds, "density_column": dc, "model_id": mid}
    for ds in TRAIN_DATASETS
    for dc in density_columns
    for mid in train_cfg["models"]
]

print(f"{len(experiments)} fine-tunes planned:")
for ex in experiments:
    mid_slug = ex['model_id'].replace('/', '_')
    tag = f"{mid_slug}__{ex['dataset']}__{ex['density_column'] or 'no_density'}"
    print(f"  {tag}")

14 fine-tunes planned:
  answerdotai_ModernBERT-base__toxigen__no_density
  tomh_toxigen_roberta__toxigen__no_density
  answerdotai_ModernBERT-base__toxigen__density_k5_ratio
  tomh_toxigen_roberta__toxigen__density_k5_ratio
  answerdotai_ModernBERT-base__toxigen__density_pca_k5_ratio
  tomh_toxigen_roberta__toxigen__density_pca_k5_ratio
  answerdotai_ModernBERT-base__toxigen__density_k100_ratio
  tomh_toxigen_roberta__toxigen__density_k100_ratio
  answerdotai_ModernBERT-base__toxigen__density_pca_k100_ratio
  tomh_toxigen_roberta__toxigen__density_pca_k100_ratio
  answerdotai_ModernBERT-base__toxigen__density_k1000_ratio
  tomh_toxigen_roberta__toxigen__density_k1000_ratio
  answerdotai_ModernBERT-base__toxigen__density_pca_k1000_ratio
  tomh_toxigen_roberta__toxigen__density_pca_k1000_ratio

## 3. Fine-Tuning Runs

Each run loads `outputs/2_embeddings/{dataset}/{model_slug}/densities.csv`,  
fine-tunes the model, and saves the checkpoint + `metrics.json` to `outputs/3_training/`.

In [4]:
all_metrics = {}

for ex in experiments:
    ds = ex["dataset"]
    dc = ex["density_column"]
    mid = ex["model_id"]
    mid_slug = mid.replace('/', '_')
    dataset_tag = ds

    density_csv = os.path.join(EMBEDDINGS_ROOT, ds, MODEL_SLUG, "densities.csv")
    if not os.path.exists(density_csv):
        print(f"[SKIP] {density_csv} not found")
        continue

    # Clone config and set density column for this run
    from dataclasses import replace
    run_config = TrainingConfig(
        model_id      = mid,
        batch_size    = base_config.batch_size,
        learning_rate = base_config.learning_rate,
        num_epochs    = base_config.num_epochs,
        max_length    = base_config.max_length,
        random_state  = base_config.random_state,
        output_root   = base_config.output_root,
        density_column= dc,
    )

    run_name = f"{mid_slug}__{run_config.run_name(dataset_tag)}"
    metrics_path = os.path.join(run_config.output_dir(dataset_tag), "metrics.json")

    if os.path.exists(metrics_path):
        print(f"[CACHE] {run_name} — loading existing metrics")
        with open(metrics_path) as f:
            all_metrics[run_name] = json.load(f)
        continue

    print(f"\n{'='*60}")
    print(f"Training: {run_name}")
    print(f"{'='*60}")
    metrics = train(density_csv=density_csv, dataset_tag=dataset_tag, config=run_config)
    all_metrics[run_name] = metrics

print("\nAll fine-tuning runs complete.")

[CACHE] answerdotai_ModernBERT-base__toxigen__no_density — loading existing metrics

============================================================
Training: tomh_toxigen_roberta__toxigen__no_density
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 52969.34 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 63114.77 examples/s]
Loading weights: 100%|██████████| 393/393 [00:00<00:00, 31001.72it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.88s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.31s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.35s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.83s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.07s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.71s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.02s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.76s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.16s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.78s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.78s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.12s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.03s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.28s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.74s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.13s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.91s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.59s/it]

Writing model shards: 100%|██████████| 1/1 [00:17<00:00, 17.72s/it]

[CACHE] answerdotai_ModernBERT-base__toxigen__density_k5_ratio — loading existing metrics

============================================================
Training: tomh_toxigen_roberta__toxigen__density_k5_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 60053.41 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 58468.73 examples/s]
Loading weights: 100%|██████████| 393/393 [00:00<00:00, 40865.76it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.08s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.12s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.88s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.77s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.97s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.28s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 16.00s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.88s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.04s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.59s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.12s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.08s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.96s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.80s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.90s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.83s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.76s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.83s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.14s/it]

Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.65s/it]

[CACHE] answerdotai_ModernBERT-base__toxigen__density_pca_k5_ratio — loading existing metrics

============================================================
Training: tomh_toxigen_roberta__toxigen__density_pca_k5_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 59533.29 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 57016.50 examples/s]
Loading weights: 100%|██████████| 393/393 [00:00<00:00, 39385.49it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.59s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 16.00s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.06s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.06s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.14s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.85s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.23s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.14s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.91s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.08s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.17s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.16s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.93s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.10s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.32s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.65s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.09s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.47s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.53s/it]

Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.84s/it]

[CACHE] answerdotai_ModernBERT-base__toxigen__density_k100_ratio — loading existing metrics

============================================================
Training: tomh_toxigen_roberta__toxigen__density_k100_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 59307.84 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 58845.91 examples/s]
Loading weights: 100%|██████████| 393/393 [00:00<00:00, 38440.37it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.53s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.07s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.92s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.74s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.67s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.13s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.90s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.02s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.88s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.04s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.98s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.17s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.65s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.92s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.84s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.07s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.22s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.80s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.19s/it]

Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.77s/it]

[CACHE] answerdotai_ModernBERT-base__toxigen__density_pca_k100_ratio — loading existing metrics

============================================================
Training: tomh_toxigen_roberta__toxigen__density_pca_k100_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 59747.65 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 56868.52 examples/s]
Loading weights: 100%|██████████| 393/393 [00:00<00:00, 31266.34it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.30s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.49s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.27s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.12s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.09s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.40s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.93s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.21s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.36s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.28s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.98s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.17s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.93s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.95s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 16.00s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.01s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.92s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.71s/it]

Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.96s/it]

[CACHE] answerdotai_ModernBERT-base__toxigen__density_k1000_ratio — loading existing metrics

============================================================
Training: tomh_toxigen_roberta__toxigen__density_k1000_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 61513.05 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 59082.83 examples/s]
Loading weights: 100%|██████████| 393/393 [00:00<00:00, 45356.93it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.22s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.50s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.33s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.35s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.98s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.83s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.27s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.25s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.02s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.99s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.16s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.84s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.99s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.70s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.92s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.46s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.44s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.76s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.28s/it]

Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.96s/it]

[CACHE] answerdotai_ModernBERT-base__toxigen__density_pca_k1000_ratio — loading existing metrics

============================================================
Training: tomh_toxigen_roberta__toxigen__density_pca_k1000_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 62444.85 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 59440.46 examples/s]
Loading weights: 100%|██████████| 393/393 [00:00<00:00, 45186.59it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.68s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.15s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.33s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.31s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.28s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.64s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.28s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.30s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.95s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.33s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.13s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.99s/it]
Writing model shards: 100%|██████████| 1/1 [00:15<00:00, 15.96s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.19s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.45s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.25s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.35s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.67s/it]
Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.05s/it]

Writing model shards: 100%|██████████| 1/1 [00:16<00:00, 16.57s/it]

All fine-tuning runs complete.

## 4. LLM Baselines

Requires Ollama running locally (`ollama serve`).  
Runs zero-shot, context, and few-shot classification on the Russian test split.

In [5]:
RUN_BASELINES = False  # set True to run (requires Ollama)

if RUN_BASELINES:
    # Use the Russian annotated test set
    russian_test_csv = os.path.join(PREPROCESSED_ROOT, "russian", "test.csv")
    if os.path.exists(russian_test_csv):
        baseline_results = run_baselines(
            test_csv=russian_test_csv,
            dataset_tag="russian_annotated",
            config=base_config,
        )
        print("Baseline results:")
        for mode, metrics in baseline_results.items():
            print(f"  {mode}: F1={metrics['f1']:.4f}  Acc={metrics['accuracy']:.4f}")
    else:
        print(f"Russian test CSV not found at {russian_test_csv}")
else:
    print("Baselines skipped (RUN_BASELINES=False).")

Baselines skipped (RUN_BASELINES=False).

## 5. Results Summary

In [6]:
if all_metrics:
    rows = []
    for run_name, m in all_metrics.items():
        parts = run_name.split("__", 2)
        rows.append({
            "run": run_name,
            "model": parts[0],
            "dataset": parts[1] if len(parts) > 1 else "n/a",
            "density": parts[2] if len(parts) > 2 else "n/a",
            "f1":               m.get("f1", float("nan")),
            "accuracy":         m.get("accuracy", float("nan")),
            "balanced_accuracy": m.get("balanced_accuracy", float("nan")),
            "auc_roc":          m.get("auc_roc", float("nan")),
        })

    summary = pd.DataFrame(rows).sort_values("f1", ascending=False)
    display(summary.style.format({
        "f1": "{:.4f}",
        "accuracy": "{:.4f}",
        "balanced_accuracy": "{:.4f}",
        "auc_roc": "{:.4f}",
    }))
else:
    print("No metrics collected yet — run the training cells first.")