# 03 — Training

Fine-tune encoder models and run LLM baselines.  
All runs use the same hyperparameters — the only variable is which density column is used for weighting.

**Sections**
1. Configuration
2. Define experiments (dataset × density column)
3. Fine-tuning runs
4. LLM baselines
5. Results summary

In [1]:
import sys, os
if os.getcwd().endswith('notebooks'):
    os.chdir('..')

import json
import yaml
import pandas as pd

from src.training import TrainingConfig, train, run_baselines

c:\Users\Alexandre\miniconda3\envs\faiss2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Configuration

Edit `TrainingConfig` fields below to change model, hyperparameters, or output paths.  
All experiments in this notebook share the same config — only `density_column` varies per run.

In [2]:
CONFIG_PATH = "configs/datasets.yaml"
with open(CONFIG_PATH) as f:
    cfg = yaml.safe_load(f)

EMBEDDINGS_ROOT   = cfg["embedding"]["output_root"]
PREPROCESSED_ROOT = cfg["preprocessing"]["output_root"]
MODEL_NAME        = cfg["embedding"]["models"][0]
MODEL_SLUG        = MODEL_NAME.replace("/", "_")
K_VALUES          = cfg["embedding"]["k_values"]

# Russian is reference-only: not used for fine-tuning, only for density + eval
TRAIN_DATASETS    = cfg.get("train_datasets", ["toxigen"])

train_cfg = cfg["training"]

base_config = TrainingConfig(
    model_id     = train_cfg["models"][0],
    batch_size   = train_cfg["batch_size"],
    learning_rate= train_cfg["learning_rate"],
    num_epochs   = train_cfg["epochs"],
    max_length   = train_cfg["max_length"],
    random_state = train_cfg["random_state"],
    output_root  = train_cfg["output_root"],
)

print("Model          :", base_config.model_id)
print("Epochs         :", base_config.num_epochs)
print("LR             :", base_config.learning_rate)
print("Train datasets :", TRAIN_DATASETS)
print("Output         :", base_config.output_root)

Model          : answerdotai/ModernBERT-base
Epochs         : 1
LR             : 2e-5
Train datasets : ['toxigen']
Output         : outputs/3_training

## 2. Define Experiments

Each experiment is `(dataset, density_column)`.  
- `density_column = None` → train without weighting (baseline encoder)
- `density_column = 'density_k5_ratio'` → weight by Russian/All ratio at K=5 on raw embeddings
- `density_column = 'density_pca_k5_ratio'` → same but PCA space

Edit the list below to add/remove experiments.

In [3]:
# Build experiment list: one fine-tune per (train_dataset × density_column)
# Russian is excluded — it is the reference group used for density, not for training.
density_columns = [None]  # baseline: no weighting
for k in K_VALUES:
    density_columns.append(f"density_k{k}_ratio")       # raw space
    density_columns.append(f"density_pca_k{k}_ratio")   # PCA space

experiments = [
    {"dataset": ds, "density_column": dc}
    for ds in TRAIN_DATASETS
    for dc in density_columns
]

print(f"{len(experiments)} fine-tunes planned:")
for ex in experiments:
    tag = f"{ex['dataset']}__{ex['density_column'] or 'no_density'}"
    print(f"  {tag}")

7 fine-tunes planned:
  toxigen__no_density
  toxigen__density_k5_ratio
  toxigen__density_pca_k5_ratio
  toxigen__density_k100_ratio
  toxigen__density_pca_k100_ratio
  toxigen__density_k1000_ratio
  toxigen__density_pca_k1000_ratio

## 3. Fine-Tuning Runs

Each run loads `outputs/2_embeddings/{dataset}/{model_slug}/densities.csv`,  
fine-tunes the model, and saves the checkpoint + `metrics.json` to `outputs/3_training/`.

In [4]:
all_metrics = {}

for ex in experiments:
    ds = ex["dataset"]
    dc = ex["density_column"]
    dataset_tag = ds

    density_csv = os.path.join(EMBEDDINGS_ROOT, ds, MODEL_SLUG, "densities.csv")
    if not os.path.exists(density_csv):
        print(f"[SKIP] {density_csv} not found")
        continue

    # Clone config and set density column for this run
    from dataclasses import replace
    run_config = TrainingConfig(
        model_id      = base_config.model_id,
        batch_size    = base_config.batch_size,
        learning_rate = base_config.learning_rate,
        num_epochs    = base_config.num_epochs,
        max_length    = base_config.max_length,
        random_state  = base_config.random_state,
        output_root   = base_config.output_root,
        density_column= dc,
    )

    run_name = run_config.run_name(dataset_tag)
    metrics_path = os.path.join(run_config.output_dir(dataset_tag), "metrics.json")

    if os.path.exists(metrics_path):
        print(f"[CACHE] {run_name} — loading existing metrics")
        with open(metrics_path) as f:
            all_metrics[run_name] = json.load(f)
        continue

    print(f"\n{'='*60}")
    print(f"Training: {run_name}")
    print(f"{'='*60}")
    metrics = train(density_csv=density_csv, dataset_tag=dataset_tag, config=run_config)
    all_metrics[run_name] = metrics

print("\nAll fine-tuning runs complete.")

============================================================
Training: toxigen__no_density
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 57054.28 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 55584.75 examples/s]
Loading weights: 100%|██████████| 136/136 [00:00<00:00, 12816.82it/s]
[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.60s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.90s/it]
Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.01s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.72s/it]
Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.16s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.65s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.79s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.53s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.81s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.59s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.63s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.77s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.94s/it]

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.51s/it]

============================================================
Training: toxigen__density_k5_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 53931.47 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 59618.66 examples/s]
Loading weights: 100%|██████████| 136/136 [00:00<00:00, 11806.14it/s]
[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.53s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.90s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.87s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.76s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.95s/it]
Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.00s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.83s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.66s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.82s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.57s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.81s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.93s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.83s/it]

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.97s/it]

============================================================
Training: toxigen__density_pca_k5_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 55562.05 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 55306.89 examples/s]
Loading weights: 100%|██████████| 136/136 [00:00<00:00, 10411.50it/s]
[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.93s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.89s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.92s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.90s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.86s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.82s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.91s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.76s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.91s/it]
Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.05s/it]
Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.20s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.94s/it]
Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.01s/it]

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.97s/it]

============================================================
Training: toxigen__density_k100_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 52097.23 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 50889.25 examples/s]
Loading weights: 100%|██████████| 136/136 [00:00<00:00, 8827.24it/s]
[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.

Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.05s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.74s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.84s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.84s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.92s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.76s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.60s/it]
Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.02s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.88s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.59s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.61s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.87s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.97s/it]

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.75s/it]

============================================================
Training: toxigen__density_pca_k100_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:04<00:00, 49588.77 examples/s]
Map: 100%|██████████| 50190/50190 [00:01<00:00, 49431.90 examples/s]
Loading weights: 100%|██████████| 136/136 [00:00<00:00, 8416.95it/s]
[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.73s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.72s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.70s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.95s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.65s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.96s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.64s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.76s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.98s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.85s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.57s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.54s/it]

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.95s/it]

============================================================
Training: toxigen__density_k1000_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 51994.24 examples/s]
Map: 100%|██████████| 50190/50190 [00:01<00:00, 44736.12 examples/s]
Loading weights: 100%|██████████| 136/136 [00:00<00:00, 7558.71it/s]
[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.82s/it]
Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.06s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.96s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.85s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.90s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.93s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.83s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.97s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.82s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.83s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.87s/it]
Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.00s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.88s/it]

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.81s/it]

============================================================
Training: toxigen__density_pca_k1000_ratio
============================================================

Map: 100%|██████████| 200758/200758 [00:03<00:00, 53993.65 examples/s]
Map: 100%|██████████| 50190/50190 [00:00<00:00, 51070.85 examples/s]
Loading weights: 100%|██████████| 136/136 [00:00<00:00, 10317.16it/s]
[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.

Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.85s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.94s/it]
Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.14s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.87s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.68s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.86s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.90s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.94s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.95s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.78s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.72s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.85s/it]

Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.02s/it]

All fine-tuning runs complete.

## 4. LLM Baselines

Requires Ollama running locally (`ollama serve`).  
Runs zero-shot, context, and few-shot classification on the Russian test split.

In [5]:
RUN_BASELINES = False  # set True to run (requires Ollama)

if RUN_BASELINES:
    # Use the Russian annotated test set
    russian_test_csv = os.path.join(PREPROCESSED_ROOT, "russian", "test.csv")
    if os.path.exists(russian_test_csv):
        baseline_results = run_baselines(
            test_csv=russian_test_csv,
            dataset_tag="russian_annotated",
            config=base_config,
        )
        print("Baseline results:")
        for mode, metrics in baseline_results.items():
            print(f"  {mode}: F1={metrics['f1']:.4f}  Acc={metrics['accuracy']:.4f}")
    else:
        print(f"Russian test CSV not found at {russian_test_csv}")
else:
    print("Baselines skipped (RUN_BASELINES=False).")

Baselines skipped (RUN_BASELINES=False).

## 5. Results Summary

In [6]:
if all_metrics:
    rows = []
    for run_name, m in all_metrics.items():
        parts = run_name.split("__", 1)
        rows.append({
            "run": run_name,
            "dataset": parts[0],
            "density": parts[1] if len(parts) > 1 else "n/a",
            "f1":               m.get("f1", float("nan")),
            "accuracy":         m.get("accuracy", float("nan")),
            "balanced_accuracy": m.get("balanced_accuracy", float("nan")),
            "auc_roc":          m.get("auc_roc", float("nan")),
        })

    summary = pd.DataFrame(rows).sort_values("f1", ascending=False)
    display(summary.style.format({
        "f1": "{:.4f}",
        "accuracy": "{:.4f}",
        "balanced_accuracy": "{:.4f}",
        "auc_roc": "{:.4f}",
    }))
else:
    print("No metrics collected yet — run the training cells first.")